/**
 * Contract test for the checked-in LobeHub manifest (`lhm.plugin.json`).
 *
 * The manifest is generated by `lhm plugin init` inspecting the stdio server
 * with the inline secret sink (see docs/DISCOVERABILITY.md). Only its version is
 * otherwise contract-tested, so a public tool change (new/removed tool, edited
 * description, changed schema or annotation) could leave the LobeHub listing
 * stale while every other fixture still passes. This test rebuilds the full
 * inline-sink surface in-process and asserts the manifest still matches the live
 * tool names, descriptions, input-schema shape, and annotations.
 */

import { createServer, getRegisteredTools } from "../../src/server";
import { readJson } from "./support";

interface LhmTool {
  name: string;
  description: string;
  inputSchema?: {
    properties?: Record<string, unknown>;
    required?: string[];
  };
  annotations?: Record<string, boolean>;
}

const lhm = readJson<{ tools: LhmTool[] }>("lhm.plugin.json");
const lhmByName = Object.fromEntries(lhm.tools.map((tool) => [tool.name, tool]));

// ── Zod-mini schema helpers (mirrors tools-schema.contract.test.ts) ───────────

function getShape(schema: any): Record<string, any> {
  return schema?.def?.shape ?? {};
}

function isRequired(fieldSchema: any): boolean {
  const t = fieldSchema?.def?.type;
  return t !== "optional" && t !== "default";
}

function propertyNames(schema: any): string[] {
  return Object.keys(getShape(schema)).sort();
}

function requiredKeys(schema: any): string[] {
  return Object.entries(getShape(schema))
    .filter(([, value]) => isRequired(value))
    .map(([key]) => key)
    .sort();
}

let tools: Record<string, any>;

beforeAll(() => {
  const server = createServer({
    applicationKeyId: "test",
    applicationKey: "test",
    appKeyId: "test",
    appKey: "test",
    masterKeyId: "test",
    masterKey: "test",
    region: "us-west-004",
    allowLocalFiles: true,
    fileRoot: null,
    // The LobeHub manifest is generated with the inline sink so the durable-
    // secret tools advertise their real inputs instead of compatibility stubs.
    secretSink: { mode: "inline" },
  });
  tools = getRegisteredTools(server) ?? {};
});

describe("lhm.plugin.json manifest drift", () => {
  it("lists exactly the live inline-sink tool names", () => {
    expect(lhm.tools.map((tool) => tool.name).sort()).toEqual(Object.keys(tools).sort());
  });

  it("matches every live tool's description, schema shape, and annotations", () => {
    for (const [name, tool] of Object.entries(tools)) {
      const manifestTool = lhmByName[name];
      expect(manifestTool, `tool ${name} missing from lhm.plugin.json`).toBeDefined();
      expect(manifestTool.description, `description drift for ${name}`).toBe(tool.description);
      expect(manifestTool.annotations, `annotation drift for ${name}`).toEqual(tool.annotations);
      expect(
        Object.keys(manifestTool.inputSchema?.properties ?? {}).sort(),
        `schema property drift for ${name}`,
      ).toEqual(propertyNames(tool.inputSchema));
      expect(
        (manifestTool.inputSchema?.required ?? []).slice().sort(),
        `required-field drift for ${name}`,
      ).toEqual(requiredKeys(tool.inputSchema));
    }
  });
});
